version: "3.9"

services:
  db:
    image: postgres:16
    container_name: weather-db
    environment:
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: weatherpass
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: