name: Weather Station Pipeline

# Specifies branches, but all work is on main so TODO remove?
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Syntactic sugar section, required for function but nonspecific to this project v
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy requests flask
# Syntactic sugar section, required for function but nonspecific to this project ^
# Compile all files except rest_api.py
      - name: Build check
        run: |
          python -m py_compile sensor.py sampler.py transformer.py
# Run the entire project for X seconds, || [ $? -eq 124 ] is included ST when the time expires github actions wont see it as a failure
      - name: Run transformer check
        run: |
          timeout 9s python transformer.py || [ $? -eq 124 ]
# Print status of pipeline health to the terminal, 
#this basically tells us if our project ran from head to toe without fault
      - name: Report success
        if: success()
        run: echo "Pipeline completed."
      - name: Report failure
        if: failure()
        run: echo "Pipeline failed."